# -*- coding: utf-8 -*-
"""Assignment_1_Homework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GdWjwCDIDoT3Tzd1AkUi2qM334G7Hpv
"""

import requests

from bs4 import BeautifulSoup

import pandas as pd

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
}

url="https://en.wikipedia.org/wiki/List_of_active_Indian_military_aircraft"

response=requests.get(url,headers=headers)

print(response.content)

soup=BeautifulSoup(response.content,'html.parser')

soup

data=soup.find('table',class_='wikitable')

data

data.find_all('tr')

name=[]

for i in data.find_all('tr')[2:]:
    name.append(i.find('a').text)
name

aircraft_name=[]
i=0
while i<len(name):
  aircraft_name.append(name[i])
  i+=2
aircraft_name

type=[]
i=1
while i<len(name):
  type.append(name[i])
  i+=2
type

d=pd.DataFrame(aircraft_name)
e=pd.DataFrame(type)
d.to_csv("assgn1_homework.csv")
e.to_csv("assgn1_homework.csv")

