# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ITsq3MWBXNvRgmrDGvAmcqrJxCvKCbs
"""

import requests

from bs4 import BeautifulSoup

import pandas as pd

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
}

url="https://www.imdb.com/chart/top/"

response=requests.get(url,headers=headers)

print(response.content)

soup=BeautifulSoup(response.content,'html.parser')

soup

data=soup.find('h3')

data

soup.find_all('h3',class_='ipc-title__text')

el=[]
for i in soup.find_all('h3',class_='ipc-title__text'):
  el.append(i.text)

el.pop()

el.pop(0)

el

print("Movies nams are:")
print(el)



"""2ND QUES"""

url2="https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"

response2 = requests.get(url2)

print(response2.content)

soup2 = BeautifulSoup(response2.text, 'html.parser')
soup2

# class='wikitable sortable mw-datatable sticky-header-multi sort-under plainrowheaders jquery-tablesorter'

table=soup.find('table',class_='wikitable')

table

table.find_all('tr')

table.find_all('tr')[2:]

states=[]

for i in table.find_all('tr')[2:]:
    states.append(i.find('a').text)
states

population=[]

for i in table.find_all('tr')[2:]:
    population.append(i.find('div').text)
population

a=dict(zip(states,population))

print("Countries and their populations are:")
print(a)

